#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 25 14:27:54 2021

@author: tangzhe
"""

#将两个csv文件按列合并为一个csv
import pandas as pd

# df = pd.read_csv('./face.csv')
df1 = pd.read_csv('df1.csv')
df2 = pd.read_csv('df2.csv')
result = pd.concat([df1, df2], axis=0)

result.to_csv('result.csv',index=False)


