# -*- coding:utf-8 -*-
# @Time : 2021/11/8 7:20 下午
# @Author: tangzhetim
# @File : file_merge.py
# @brief : This file is used to merge the data generated by MOGP with the original data.
# It is important to note that the data generated by MOGP needs to be at the scale of the
# entire building. In addition, pay attention to the column order when merging files. Therefore,
# you are not advised to change the write order. The amount of data is not covered in this document.
import pandas as pd
import numpy as np
f1 = pd.read_csv('trainingData2_fake.csv')
f2 = pd.read_csv('/Users/tangzhe/GitHub/IndoorLoc_a_test/data_silce/building0.csv')
f2.loc[:,"FLOOR"] *= 3
file = [f1,f2]
train = pd.concat(file)
train.to_csv("trainingData2" + ".csv", index=0, sep=',')
train_new = pd.read_csv('trainingData2.csv')
train_new=train_new.drop(['BUILDINGID','SPACEID','RELATIVEPOSITION','USERID','PHONEID','TIMESTAMP'],axis=1)
train_new.loc[:,"BUILDINGID"] = np.zeros((len(train_new),1),dtype=int)
train_new.loc[:,"SPACEID"] = np.zeros((len(train_new),1),dtype=int)
train_new.loc[:,"RELATIVEPOSITION"] = np.zeros((len(train_new),1),dtype=int)
train_new.loc[:,"USERID"] = np.zeros((len(train_new),1),dtype=int)
train_new.loc[:,"PHONEID"] = np.zeros((len(train_new),1),dtype=int)
train_new.loc[:,"TIMESTAMP"] = np.zeros((len(train_new),1),dtype=int)
train_new.to_csv("trainingData2" + ".csv", index=0, sep=',')

#To convert the floors in the validation file to data in meters.
# ff = pd.read_csv('/Users/tangzhe/GitHub/IndoorLoc_a_test/data_silce/validationData2.csv')
# ff.loc[:,"FLOOR"] *=3
# ff.to_csv("/Users/tangzhe/GitHub/IndoorLoc_a_test/data_silce/validationData2.csv",index=0,sep=',')